language: csharp
solution: WindowsFormsTempConverter.sln
install:
  - nuget restore WindowsFormsTempConverter.sln
  - nuget install NUnit.ConsoleRunner -Version 3.6.0 -OutputDirectory testrunner 
script:
  - xbuild /p:Configuration=Release WindowsFormsTempConverter.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe ./WindowsFormsTempConverter.sln.Test/bin/Release/WindowsFormsTempConverter.sln.Test.dll
notifications:
  email: false
